version: '3.8'

services:
    db:
        image: mysql
        container_name: vatsim-radar-prebuilt-db
        cap_add:
            - SYS_NICE
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=radar
            - MYSQL_ROOT_PASSWORD=localhost
        ports:
            - '127.0.0.1:3307:3306'
            - '100.111.33.72:3307:3306'
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            timeout: 5s
            interval: 5s
            retries: 40
        volumes:
            - ./.config/db:/var/lib/mysql
        networks:
            radar-backend:
                aliases:
                    - db
        extra_hosts:
            - "host.docker.internal:host-gateway"

    redis:
        image: redis
        container_name: vatsim-radar-prebuilt-redis
        command: redis-server /usr/local/etc/redis/redis.conf --requirepass RADAR --bind 0.0.0.0
        expose:
            - 6379
        ports:
            - '100.111.33.72:6379:6379'
        environment:
            - REDIS_APPLICATION_MODE=master
        volumes:
            - ./.config/redis.conf:/usr/local/etc/redis/redis.conf
            - ./.config/redis:/data
        networks:
            radar-backend:
                aliases:
                    - redis
        extra_hosts:
            - "host.docker.internal:host-gateway"

    questdb:
        image: questdb/questdb:9.4.3
        container_name: vatsim-radar-questdb
        environment:
            - QDB_LOG_W_STDOUT_LEVEL=ERROR
            - QDB_SHARED_WORKER_COUNT=1
        ports:
            - "127.0.0.1:9000:9000"
            - "127.0.0.1:9009:9009"
            - "127.0.0.1:8812:8812"
            - "127.0.0.1:9003:9003"
            - "100.111.33.72:9000:9000"
            - "100.111.33.72:9009:9009"
            - "100.111.33.72:8812:8812"
            - "100.111.33.72:9003:9003"
        volumes:
            - ./.config/questdb:/var/lib/questdb
        networks:
            radar-backend:
                aliases:
                    - questdb
        extra_hosts:
            - "host.docker.internal:host-gateway"

networks:
    radar-backend:
        name: vatsim-radar-backend
